/// Flutter icons CustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_accepted = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_add = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_delete = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_remove = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_square = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_square_filled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ps5 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_category = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_circle = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_filled = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_filled = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender_2 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete2 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike_filled = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_filled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_square = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_hide = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_show = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter2 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foreign = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_filled = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_filled = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_filled = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_circle = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_filled = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_square = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
